// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an event's routing actor was established. Only `Native` and `Derived`
 * are semantic attribution; `ScopeFallback` routes a control or unattributed
 * evidence envelope to the root without claiming the root produced it.
 */
export type ActorAttribution = "native" | "derived" | "scope_fallback";
