// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorAttribution } from "./ActorAttribution";

/**
 * Root + actor identity carried by every event.
 */
export type ActorRef = { 
/**
 * RFC 012A canonical session key of the observed root.
 */
session_key: string, 
/**
 * Native session id as the adapter names it.
 */
native_session_id: string, 
/**
 * Canonical actor-run key. Equals the root run for root-produced events.
 */
actor_run_key: string, attribution: ActorAttribution, };
