// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObserverEventId } from "./ObserverEventId";

/**
 * The observer failed terminally and makes no further continuity claim.
 */
export type ObserverErrorEvent = { event_id: ObserverEventId, sequence: number, scope_epoch: number, message: string, observed_at: number, };
