// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObserverEventId } from "./ObserverEventId";
import type { OverflowReason } from "./OverflowReason";

/**
 * Continuity was lost; the named epoch is invalid and its undelivered events
 * were discarded. A full replacement snapshot follows in a new epoch.
 */
export type OverflowEvent = { event_id: ObserverEventId, sequence: number, 
/**
 * The epoch being abandoned.
 */
scope_epoch: number, reason: OverflowReason, 
/**
 * Last sequence that was contiguous in the invalidated epoch.
 */
last_contiguous_sequence: number, observed_at: number, };
