// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { ObserverEventId } from "./ObserverEventId";
import type { ObserverPhase } from "./ObserverPhase";
import type { SourcePosition } from "./SourcePosition";

/**
 * A native record the adapter did not interpret.
 *
 * RFC 012D section 15 keeps this as bounded evidence rather than dropping it:
 * a consumer that sees these knows its coverage has a hole, instead of
 * silently missing facts. No native values travel here — only how large the
 * record was and what it hashes to.
 */
export type UnknownEvidenceEvent = { event_id: ObserverEventId, sequence: number, scope_epoch: number, phase: ObserverPhase, source: SourcePosition, 
/**
 * The adapter's guess at the family, when it offered one.
 */
family_hint: string | null, 
/**
 * Size of the record that was not interpreted.
 */
observed_bytes: number, actor: ActorRef, observed_at: number, };
