/**
 * Native addon loader — `@vibecook/spaghetti-sdk-native`.
 *
 * The Rust engine ships as a separate native addon. The production SDK
 * requires it; a missing or incompatible binary is an actionable startup
 * error and never selects a second ingest authority.
 *
 * ## One definition per type
 *
 * Nothing here re-declares a shape the addon already declares. Every type that
 * crosses the boundary is generated from Rust — napi-rs writes
 * `crates/spaghetti-napi/index.d.ts` for the request DTOs a caller composes,
 * `ts-rs` writes `./generated/` for the result contracts — and this module
 * renames them into the `Spaghetti*` namespace the public API uses. The
 * hand-written mirror that used to live here (2,100 lines of `SpaghettiEngine*`
 * interfaces copied from `index.d.ts`) is gone; RFC 012 landing plan §5.4
 * forbids it, and it had already drifted from what Rust actually returns.
 *
 * ## How results cross
 *
 * Engine results cross N-API as a JSON string, encoded on the Rust worker
 * thread (`encode_json` in `napi_engine.rs`). {@link openSpaghettiEngine}
 * decodes them once, here, so every other module sees ordinary objects typed
 * by the generated contracts. That is why {@link SpaghettiEngine} below is
 * declared in terms of `./generated/` types while the addon's own declaration
 * says `Promise<string>`: this module is the decode boundary, and the types on
 * either side of it are both generated from the same Rust definition.
 */

import { createRequire } from 'node:module';

import type { IngestEngine } from './settings.js';

/**
 * Request DTOs the caller composes, generated by napi-rs.
 *
 * These are not mirrors of engine structs: their fields are optional where the
 * resolved engine request's are required, and Rust applies the defaults.
 */
export type {
  EngineCatalogPageOptions as SpaghettiCatalogPageOptions,
  EngineCatalogSessionPageOptions as SpaghettiCatalogSessionPageOptions,
  EngineAdapterObservationOptions as SpaghettiEngineAdapterObservationOptions,
  EngineAdapterReconcileOptions as SpaghettiEngineAdapterReconcileOptions,
  EngineArtifactPageOptions as SpaghettiEngineArtifactPageOptions,
  EngineCapabilityPageOptions as SpaghettiEngineCapabilityPageOptions,
  EngineChangeCursor as SpaghettiEngineChangeCursor,
  EngineChangeReplayOptions as SpaghettiEngineChangeReplayOptions,
  EngineCommitWaitOptions as SpaghettiEngineCommitWaitOptions,
  EngineConfiguredObservationOptions as SpaghettiEngineConfiguredObservationOptions,
  EngineConfiguredObservationSourceOptions as SpaghettiEngineConfiguredObservationSourceOptions,
  EngineDelegationPageOptions as SpaghettiEngineDelegationPageOptions,
  EngineFactFamilyCoverageOptions as SpaghettiEngineFactFamilyCoverageOptions,
  EngineFactFamilyReplayOptions as SpaghettiEngineFactFamilyReplayOptions,
  EngineHistoryPageOptions as SpaghettiEngineHistoryPageOptions,
  EngineHistorySessionPageOptions as SpaghettiEngineHistorySessionPageOptions,
  EngineMemoryDocumentPageOptions as SpaghettiEngineMemoryDocumentPageOptions,
  EngineMessagePageOptions as SpaghettiEngineMessagePageOptions,
  EngineObservationOptions as SpaghettiEngineObservationOptions,
  EngineOpenOptions as SpaghettiEngineOpenOptions,
  EngineReconcileOptions as SpaghettiEngineReconcileOptions,
  EngineRuntimeSnapshotOptions as SpaghettiEngineRuntimeSnapshotOptions,
  EngineSearchPageOptions as SpaghettiEngineSearchPageOptions,
  EngineTaskCollectionPageOptions as SpaghettiEngineTaskCollectionPageOptions,
  EngineTaskPageOptions as SpaghettiEngineTaskPageOptions,
  EngineTeamInboxMessagePageOptions as SpaghettiEngineTeamInboxMessagePageOptions,
  EngineTeamPageOptions as SpaghettiEngineTeamPageOptions,
  EngineTeamScopedPageOptions as SpaghettiEngineTeamScopedPageOptions,
  EngineTimelinePageOptions as SpaghettiEngineTimelinePageOptions,
  EngineToolResultPageOptions as SpaghettiEngineToolResultPageOptions,
  EngineUsageOptions as SpaghettiEngineUsageOptions,
  EngineWorkflowMemberPageOptions as SpaghettiEngineWorkflowMemberPageOptions,
  EngineWorkflowPageOptions as SpaghettiEngineWorkflowPageOptions,
} from '@vibecook/spaghetti-sdk-native';

/**
 * Result contracts, generated from the Rust definitions by ts-rs.
 *
 * To change one of these shapes, change the Rust struct and run
 * `pnpm generate:types`; there is nothing to edit here but the name.
 */
export type {
  CatalogResolution as SpaghettiCatalogResolution,
  CatalogStartup as SpaghettiCatalogStartup,
  ArtifactDetail as SpaghettiEngineArtifact,
  ArtifactPage as SpaghettiEngineArtifactPage,
  CanonicalStats as SpaghettiEngineCanonicalStats,
  ChangeReplay as SpaghettiEngineChangeReplay,
  CheckpointPerformanceStats as SpaghettiEngineCheckpointPerformanceStats,
  CommitWaitResult as SpaghettiEngineCommitWaitResult,
  DelegationSummary as SpaghettiEngineDelegation,
  DelegationPage as SpaghettiEngineDelegationPage,
  DurableChange as SpaghettiEngineDurableChange,
  FactFamilyCoverageItem as SpaghettiEngineFactFamilyCoverageItem,
  FactFamilyCoveragePage as SpaghettiEngineFactFamilyCoveragePage,
  FactFamilyCoverageSetSummary as SpaghettiEngineFactFamilyCoverageSetSummary,
  FactFamilyReplayResult as SpaghettiEngineFactFamilyReplayResult,
  EngineHealthSnapshot as SpaghettiEngineHealth,
  HistoryProjectSummary as SpaghettiEngineHistoryProject,
  HistoryProjectIndexSummary as SpaghettiEngineHistoryProjectIndex,
  HistoryProjectPage as SpaghettiEngineHistoryProjectPage,
  HistorySessionSummary as SpaghettiEngineHistorySession,
  HistorySessionIndexSummary as SpaghettiEngineHistorySessionIndex,
  HistorySessionPage as SpaghettiEngineHistorySessionPage,
  LatencyStats as SpaghettiEngineLatencyStats,
  MemoryDocument as SpaghettiEngineMemoryDocument,
  MemoryDocumentPage as SpaghettiEngineMemoryDocumentPage,
  MessageDetail as SpaghettiEngineMessageDetail,
  MessagePage as SpaghettiEngineMessagePage,
  NamedCount as SpaghettiEngineNamedCount,
  NamedLatencyStats as SpaghettiEngineNamedLatencyStats,
  ObservationStatusSnapshot as SpaghettiEngineObservationStatus,
  EngineOverview as SpaghettiEngineOverview,
  OwnerInfo as SpaghettiEngineOwner,
  PerformanceStats as SpaghettiEnginePerformanceStats,
  PlanDetail as SpaghettiEnginePlan,
  PlanPage as SpaghettiEnginePlanPage,
  QueryPerformanceStats as SpaghettiEngineQueryPerformanceStats,
  ReconcileOutcome as SpaghettiEngineReconcileResult,
  RunStateLookup as SpaghettiEngineRunStateLookup,
  RuntimeSnapshotEntry as SpaghettiEngineRuntimeEntry,
  RuntimePresenceSnapshot as SpaghettiEngineRuntimePresence,
  RuntimeRunSnapshot as SpaghettiEngineRuntimeRun,
  RuntimeRunEvidence as SpaghettiEngineRuntimeRunEvidence,
  RuntimeSnapshot as SpaghettiEngineRuntimeSnapshot,
  SearchHit as SpaghettiEngineSearchHit,
  SearchPage as SpaghettiEngineSearchPage,
  SessionDetail as SpaghettiEngineSessionDetail,
  SessionDetails as SpaghettiEngineSessionDetails,
  SourceCapabilitySummary as SpaghettiEngineSourceCapability,
  SourceDimensionPerformanceStats as SpaghettiEngineSourceDimensionPerformanceStats,
  SourcePage as SpaghettiEngineSourcePage,
  SourcePerformanceStats as SpaghettiEngineSourcePerformanceStats,
  SourcePipelineStats as SpaghettiEngineSourcePipelineStats,
  SourceSummary as SpaghettiEngineSourceSummary,
  EngineStatusSnapshot as SpaghettiEngineStatus,
  StoragePerformanceStats as SpaghettiEngineStoragePerformanceStats,
  TaskDetail as SpaghettiEngineTask,
  TaskCollectionSummary as SpaghettiEngineTaskCollection,
  TaskCollectionPage as SpaghettiEngineTaskCollectionPage,
  TaskPage as SpaghettiEngineTaskPage,
  TeamConfigSummary as SpaghettiEngineTeamConfig,
  TeamDetails as SpaghettiEngineTeamDetails,
  TeamInboxSummary as SpaghettiEngineTeamInbox,
  TeamInboxMessage as SpaghettiEngineTeamInboxMessage,
  TeamInboxMessagePage as SpaghettiEngineTeamInboxMessagePage,
  TeamInboxPage as SpaghettiEngineTeamInboxPage,
  TeamMember as SpaghettiEngineTeamMember,
  TeamPage as SpaghettiEngineTeamPage,
  TeamSummary as SpaghettiEngineTeamSummary,
  TimelineFacets as SpaghettiEngineTimelineFacets,
  TimelineMessage as SpaghettiEngineTimelineMessage,
  TimelinePage as SpaghettiEngineTimelinePage,
  ToolResultDetail as SpaghettiEngineToolResult,
  ToolResultPage as SpaghettiEngineToolResultPage,
  UntimedUsageSummary as SpaghettiEngineUntimedUsage,
  UsageReport as SpaghettiEngineUsage,
  UsageAggregate as SpaghettiEngineUsageAggregate,
  UsageCoverageSummary as SpaghettiEngineUsageCoverage,
  UsageDay as SpaghettiEngineUsageDay,
  UsageTokenValues as SpaghettiEngineUsageTokenValues,
  UsageWindowReport as SpaghettiEngineUsageWindow,
  WorkflowDetails as SpaghettiEngineWorkflowDetails,
  WorkflowMember as SpaghettiEngineWorkflowMember,
  WorkflowMemberPage as SpaghettiEngineWorkflowMemberPage,
  WorkflowPage as SpaghettiEngineWorkflowPage,
  WorkflowSummary as SpaghettiEngineWorkflowSummary,
  WriterPerformanceStats as SpaghettiEngineWriterPerformanceStats,
} from './generated/index.js';

import type {
  EngineAdapterObservationOptions,
  EngineAdapterReconcileOptions,
  EngineArtifactPageOptions,
  EngineCapabilityPageOptions,
  EngineCatalogPageOptions,
  EngineCatalogSessionPageOptions,
  EngineChangeReplayOptions,
  EngineCommitWaitOptions,
  EngineConfiguredObservationOptions,
  EngineDelegationPageOptions,
  EngineFactFamilyCoverageOptions,
  EngineFactFamilyReplayOptions,
  EngineHistoryPageOptions,
  EngineHistorySessionPageOptions,
  EngineMemoryDocumentPageOptions,
  EngineMessagePageOptions,
  EngineObservationOptions,
  EngineReconcileOptions,
  EngineRuntimeSnapshotOptions,
  EngineSearchPageOptions,
  EngineTaskCollectionPageOptions,
  EngineTaskPageOptions,
  EngineTeamInboxMessagePageOptions,
  EngineTeamPageOptions,
  EngineTeamScopedPageOptions,
  EngineTimelinePageOptions,
  EngineToolResultPageOptions,
  EngineUsageOptions,
  EngineWorkflowMemberPageOptions,
  EngineWorkflowPageOptions,
} from '@vibecook/spaghetti-sdk-native';
import type {
  ArtifactPage,
  CanonicalStats,
  CatalogProjectPage,
  CatalogResolution,
  CatalogSessionPage,
  CatalogStartup,
  ChangeReplay,
  CommitWaitResult,
  DelegationPage,
  EngineHealthSnapshot,
  EngineOverview,
  EngineStatusSnapshot,
  FactFamilyCoveragePage,
  FactFamilyReplayResult,
  HistoryProjectPage,
  HistorySessionPage,
  MemoryDocumentPage,
  MessagePage,
  PlanPage,
  Readiness,
  ReconcileOutcome,
  RunStateLookup,
  RuntimeSnapshot,
  SearchPage,
  SessionDetails,
  SourcePage,
  TaskCollectionPage,
  TaskPage,
  TeamDetails,
  TeamInboxMessagePage,
  TeamInboxPage,
  TeamPage,
  TimelinePage,
  ToolResultPage,
  UsageReport,
  WorkflowDetails,
  WorkflowMemberPage,
  WorkflowPage,
} from './generated/index.js';

/**
 * The persistent engine handle, as the SDK sees it: results already decoded.
 *
 * Method names, arguments, and doc comments follow the addon's generated
 * declaration; the payload types are the generated ts-rs contracts rather than
 * the `string` the addon hands over before {@link openSpaghettiEngine} decodes
 * it. `engine-json-contract.test.ts` runs every method against a real engine
 * and checks the decoded result against these types.
 */
export interface SpaghettiEngine {
  /** Current lifecycle status, decoded from the addon's JSON. */
  readonly status: EngineStatusSnapshot;
  /** Probe the writer and one query worker off the JavaScript thread. */
  health(signal?: AbortSignal | undefined | null): Promise<EngineHealthSnapshot>;
  /** Execute the first typed, read-only Rust query. */
  overview(signal?: AbortSignal | undefined | null): Promise<EngineOverview>;
  /**
   * Replay one bounded, snapshot-consistent page of durable projection
   * changes. Binary keys and payloads remain lossless base64 strings.
   */
  replayChanges(
    options?: EngineChangeReplayOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<ChangeReplay>;
  /**
   * Wait off the JavaScript thread for the Rust writer to publish a newer
   * durable commit. No SQLite read is performed while the request is idle.
   */
  waitForCommit(options: EngineCommitWaitOptions, signal?: AbortSignal | undefined | null): Promise<CommitWaitResult>;
  /**
   * List catalog projects — everything discoverable, complete or explicitly
   * degraded. Available seconds after `startConfiguredObservation`, without
   * waiting for history, usage, or full-text search.
   *
   * This is a different question from `listHistoryProjects`, which reports
   * what has been decoded. Both are kept because both are asked.
   */
  listCatalogProjects(
    options?: EngineCatalogPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<CatalogProjectPage>;
  /**
   * List catalog sessions, optionally within one project. Rows carry the
   * evidence behind their project association and any competing identity.
   */
  listCatalogSessions(
    options?: EngineCatalogSessionPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<CatalogSessionPage>;
  /** Resolve a persisted external reference against the current catalog. */
  resolveCatalogEntity(externalRef: string, signal?: AbortSignal | undefined | null): Promise<CatalogResolution>;
  /**
   * Wait until every configured supervisor has finished starting.
   *
   * `startConfiguredObservation` resolves as soon as the catalog commits,
   * so watchers are still coming up behind it. Callers that need decoded
   * history await this; callers that only need the library do not.
   */
  awaitObservationStart(signal?: AbortSignal | undefined | null): Promise<EngineStatusSnapshot>;
  /**
   * The readiness vector: catalog, history, usage, capabilities, artifacts,
   * and search, each derived from committed rows.
   */
  readiness(signal?: AbortSignal | undefined | null): Promise<Readiness>;
  /**
   * List canonical projects in Rust-defined activity order. The cursor is
   * opaque, versioned, and valid only for this query.
   */
  listHistoryProjects(
    options?: EngineHistoryPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<HistoryProjectPage>;
  /**
   * List transcript-backed sessions for one canonical project. Native
   * session-index metadata is returned as explicitly sourced enrichment.
   */
  listHistorySessions(
    options: EngineHistorySessionPageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<HistorySessionPage>;
  /**
   * Read one transcript-backed canonical session and its projection counts.
   * A well-formed unknown identity returns an absent `session`.
   */
  getSession(sessionId: string, signal?: AbortSignal | undefined | null): Promise<SessionDetails>;
  /**
   * Page canonical messages for one verified project/session membership.
   * Both row count and decoded JSON payload bytes are bounded in Rust.
   */
  getMessages(options: EngineMessagePageOptions, signal?: AbortSignal | undefined | null): Promise<MessagePage>;
  /**
   * Search all canonical root and delegated messages in one FTS score
   * domain. Exact totals, filtering, snippets, and paging are Rust-owned.
   */
  search(options: EngineSearchPageOptions, signal?: AbortSignal | undefined | null): Promise<SearchPage>;
  /**
   * Read one root-and-delegated canonical timeline page plus exact session
   * facets in a single SQLite snapshot.
   */
  getTimeline(options: EngineTimelinePageOptions, signal?: AbortSignal | undefined | null): Promise<TimelinePage>;
  /** Page current child-run delegation relations for one canonical session. */
  listDelegations(
    options: EngineDelegationPageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<DelegationPage>;
  /** Page canonical workflow containers for one canonical session. */
  listWorkflows(options: EngineWorkflowPageOptions, signal?: AbortSignal | undefined | null): Promise<WorkflowPage>;
  /** Read one workflow container and its bounded native snapshot. */
  getWorkflow(workflowId: string, signal?: AbortSignal | undefined | null): Promise<WorkflowDetails>;
  /** Page native workflow members and their explicit journal evidence. */
  listWorkflowMembers(
    options: EngineWorkflowMemberPageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<WorkflowMemberPage>;
  /**
   * Page canonical project-memory documents. Exact UTF-8 content and row
   * count are bounded in Rust.
   */
  listMemoryDocuments(
    options: EngineMemoryDocumentPageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<MemoryDocumentPage>;
  /** Page canonical task collections globally or under one trusted scope. */
  listTaskCollections(
    options?: EngineTaskCollectionPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<TaskCollectionPage>;
  /** Page canonical task items for one opaque collection identity. */
  listTasks(options: EngineTaskPageOptions, signal?: AbortSignal | undefined | null): Promise<TaskPage>;
  /** Page global plan documents. No session relation is fabricated. */
  listPlans(
    options?: EngineCapabilityPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<PlanPage>;
  /** Page persisted tool-result sidecars for one verified session. */
  listToolResults(
    options: EngineToolResultPageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<ToolResultPage>;
  /**
   * Page session-scoped file-history artifacts. Arbitrary content is
   * represented as base64 and bounded by Rust before crossing N-API.
   */
  listArtifacts(options: EngineArtifactPageOptions, signal?: AbortSignal | undefined | null): Promise<ArtifactPage>;
  /** List configured source instances and their durable ingest inventory. */
  listSources(
    options?: EngineHistoryPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<SourcePage>;
  /**
   * Return one snapshot-consistent set of canonical and source-catalog
   * counts. Compatibility-cache tables are intentionally excluded.
   */
  getStats(signal?: AbortSignal | undefined | null): Promise<CanonicalStats>;
  /**
   * Return canonical response-level usage for one project or one verified
   * session. Supplying `from` and `to` adds the per-day series and the
   * contributions that no day can own.
   */
  getUsage(options: EngineUsageOptions, signal?: AbortSignal | undefined | null): Promise<UsageReport>;
  /**
   * Page normalized RFC 012A coverage for one fact family using opaque
   * common identities. The result shares one durable commit watermark and
   * never exposes native paths or object keys.
   */
  getFactFamilyCoverage(
    options: EngineFactFamilyCoverageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<FactFamilyCoveragePage>;
  /**
   * Replace one fact family's durable evidence after a caller explicitly
   * echoes the current source, digest, and coverage commit authorization.
   */
  replayFactFamily(
    options: EngineFactFamilyReplayOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<FactFamilyReplayResult>;
  /**
   * Return durable run-state and current registry-presence evidence. This
   * intentionally does not probe PIDs or synthesize freshness assessments.
   */
  getRuntimeSnapshot(
    options?: EngineRuntimeSnapshotOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<RuntimeSnapshot>;
  /**
   * Look up one canonical run without probing process liveness. A
   * well-formed unknown identity returns an absent `run`.
   */
  getRunState(runId: string, signal?: AbortSignal | undefined | null): Promise<RunStateLookup>;
  /** List current canonical teams, including inbox-only team identities. */
  listTeams(
    options?: EngineTeamPageOptions | undefined | null,
    signal?: AbortSignal | undefined | null,
  ): Promise<TeamPage>;
  /** Read one current team configuration and its bounded member snapshot. */
  getTeam(teamId: string, signal?: AbortSignal | undefined | null): Promise<TeamDetails>;
  /**
   * Page inbox summaries without returning potentially sensitive message
   * bodies in a directory listing.
   */
  listTeamInboxes(
    options: EngineTeamScopedPageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<TeamInboxPage>;
  /** Page one inbox's messages in native snapshot order. */
  listTeamInboxMessages(
    options: EngineTeamInboxMessagePageOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<TeamInboxMessagePage>;
  /**
   * Reconcile any registered adapter through the common Rust source and
   * projection transaction path.
   */
  reconcileAdapter(
    options: EngineAdapterReconcileOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<ReconcileOutcome>;
  /** Register consolidated roots and supervise any registered adapter. */
  startObservation(
    options: EngineAdapterObservationOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<EngineStatusSnapshot>;
  /**
   * Start the complete configured source set, catalog first: every source
   * commits its discovered projects and sessions before any watcher begins
   * a history scan.
   */
  startConfiguredObservation(
    options: EngineConfiguredObservationOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<CatalogStartup>;
  /** Force one running adapter supervisor through common reconciliation. */
  refreshObservation(adapterId: string, signal?: AbortSignal | undefined | null): Promise<EngineStatusSnapshot>;
  /** Stop one adapter supervisor without disposing the engine. */
  stopObservation(adapterId: string, signal?: AbortSignal | undefined | null): Promise<EngineStatusSnapshot>;
  /**
   * Reconcile the adapter-declared Claude source map through the common
   * Rust drivers, decoders, projections, and durable cursor transaction.
   */
  reconcileClaude(options: EngineReconcileOptions, signal?: AbortSignal | undefined | null): Promise<ReconcileOutcome>;
  /**
   * Register consolidated native roots before an initial scan, then keep
   * one bounded Rust supervisor reconciling Claude changes and polling.
   */
  startClaudeObservation(
    options: EngineObservationOptions,
    signal?: AbortSignal | undefined | null,
  ): Promise<EngineStatusSnapshot>;
  /** Force the running Claude supervisor through its common reconcile path. */
  refreshClaudeObservation(signal?: AbortSignal | undefined | null): Promise<EngineStatusSnapshot>;
  /** Stop native Claude watch registration without disposing the engine. */
  stopClaudeObservation(signal?: AbortSignal | undefined | null): Promise<EngineStatusSnapshot>;
  /**
   * Invalidate queued query requests. Requests submitted afterward use a
   * new cancellation epoch and remain valid.
   */
  cancelPendingQueries(): number;
  /**
   * Finalize a size-gated cold bootstrap and admit the read pool only
   * after indexes, canonical FTS, and integrity checks have converged.
   */
  completeQueryBootstrap(): Promise<EngineStatusSnapshot>;
  /** Deterministically stop readers, stop the writer, and release ownership. */
  dispose(): Promise<EngineStatusSnapshot>;
}

/**
 * Catalog and readiness names the CLI and playground import.
 */
export type {
  CatalogProjectPage as SpaghettiCatalogProjectPage,
  CatalogProjectRow as SpaghettiCatalogProject,
  CatalogSessionPage as SpaghettiCatalogSessionPage,
  CatalogSessionRow as SpaghettiCatalogSession,
  CatalogState as SpaghettiCatalogState,
  IdentityConflict as SpaghettiCatalogIdentityConflict,
  Readiness as SpaghettiReadiness,
  ReadinessField as SpaghettiReadinessField,
  ReadinessState as SpaghettiReadinessState,
} from './generated/index.js';

export type {
  SpaghettiSessionObserver as NativeSessionObserver,
  ObserverStatus as NativeSessionObserverStatus,
} from '@vibecook/spaghetti-sdk-native';

import type {
  EngineOpenOptions as SpaghettiEngineOpenOptions,
  SpaghettiEngine as NativeSpaghettiEngine,
  SpaghettiSessionObserver as NativeSessionObserver,
} from '@vibecook/spaghetti-sdk-native';

/**
 * The loaded addon's module shape.
 *
 * Declared as the module's own type rather than re-listed, so a new native
 * entry point is visible to the SDK the moment napi-rs generates it.
 */
export type NativeAddon = typeof import('@vibecook/spaghetti-sdk-native');

/**
 * Why the native addon did not load, in terms a user can act on.
 *
 * The loader reports whether the package is missing, unsupported, or cannot
 * load on the current libc. RFC 011 has no production TypeScript fallback.
 */
export class EngineUnavailableError extends Error {
  /** `process.platform` — `linux`, `darwin`, `win32`. */
  readonly platform: string;
  /** `process.arch` — `x64`, `arm64`. */
  readonly arch: string;
  /**
   * `glibc`, `musl`, or `null` off Linux.
   *
   * Worth carrying because it is the difference between "unsupported
   * platform" and "wrong artifact for a supported one" — an Alpine container
   * is x64 Linux and still cannot load a GNU build.
   */
  readonly libc: 'glibc' | 'musl' | null;
  /** Version of the addon package the SDK expects. */
  readonly expectedVersion: string;
  /** The underlying resolution failure. */
  readonly cause: unknown;

  constructor(init: {
    platform: string;
    arch: string;
    libc: 'glibc' | 'musl' | null;
    expectedVersion: string;
    cause: unknown;
  }) {
    const target = [init.platform, init.arch, init.libc].filter(Boolean).join('-');
    super(
      `Native observation addon unavailable for ${target}. ` +
        `RFC 011 requires the Rust engine; no TypeScript production fallback is enabled. ` +
        `${installHint(init.platform, init.libc)}`,
    );
    this.name = 'EngineUnavailableError';
    this.platform = init.platform;
    this.arch = init.arch;
    this.libc = init.libc;
    this.expectedVersion = init.expectedVersion;
    this.cause = init.cause;
  }
}

function installHint(platform: string, libc: 'glibc' | 'musl' | null): string {
  if (platform === 'linux' && libc === 'musl') {
    return (
      'On Alpine and other musl systems, install the musl build: ' +
      '`npm i @vibecook/spaghetti-sdk-native-linux-x64-musl` (or `-arm64-musl`).'
    );
  }
  if (platform === 'linux') {
    return (
      'Check that your glibc meets the documented minimum, or reinstall to fetch ' +
      'the prebuilt binary: `npm i @vibecook/spaghetti-sdk-native`.'
    );
  }
  return 'Reinstall to fetch the prebuilt binary: `npm i @vibecook/spaghetti-sdk-native`.';
}

/**
 * Which C library this Node was built against.
 *
 * `glibcVersionRuntime` is present in the process report on glibc and absent
 * on musl — the detection Node's own ecosystem uses, and it needs no child
 * process or filesystem probe.
 */
export function detectLibc(): 'glibc' | 'musl' | null {
  if (process.platform !== 'linux') return null;
  try {
    const header = (process.report?.getReport() as { header?: Record<string, unknown> } | undefined)?.header;
    return header && 'glibcVersionRuntime' in header ? 'glibc' : 'musl';
  } catch {
    return null;
  }
}

let cached: NativeAddon | null | undefined;
let loadFailure: EngineUnavailableError | null = null;

/**
 * Load the native addon, returning null if unavailable.
 *
 * Result is memoized — a missing addon won't be retried on subsequent calls.
 * When it fails, the reason is kept and available from
 * {@link nativeLoadFailure} rather than discarded.
 */
export function loadNativeAddon(): NativeAddon | null {
  if (cached !== undefined) return cached;

  try {
    const require = createRequire(import.meta.url);
    cached = require('@vibecook/spaghetti-sdk-native') as NativeAddon;
    loadFailure = null;
  } catch (err) {
    cached = null;
    loadFailure = new EngineUnavailableError({
      platform: process.platform,
      arch: process.arch,
      libc: detectLibc(),
      expectedVersion: expectedAddonVersion(),
      cause: err,
    });
  }

  return cached;
}

/**
 * Open the persistent Rust observation/query engine.
 *
 * This is the low-level persistent lifecycle surface. Applications normally
 * use `createObservationService()`, which owns this handle and exposes the
 * canonical client-backed product API.
 */
export function openSpaghettiEngine(options: SpaghettiEngineOpenOptions): Promise<SpaghettiEngine> {
  const addon = loadNativeAddon();
  if (!addon) {
    const failure = nativeLoadFailure();
    if (failure) throw failure;
    throw new Error('Persistent SpaghettiEngine requires the native addon, but it could not be loaded.');
  }
  return addon.openSpaghettiEngine(options).then((engine) => decodeEngineResults(engine));
}

/**
 * Attach the native store-free observer for one session tree.
 *
 * Validation is synchronous: an unusable agent root, a locator outside the
 * adapter's declared source roots, or a session id that disagrees with the
 * locator throws here rather than surfacing as an error event later.
 */
export function openNativeSessionObserver(request: string | Record<string, unknown>): NativeSessionObserver {
  const addon = loadNativeAddon();
  if (!addon) {
    const failure = nativeLoadFailure();
    if (failure) throw failure;
    throw new Error('Session observation requires the native addon, but it could not be loaded.');
  }
  if (typeof addon.observeSession !== 'function') {
    throw new Error('The loaded native addon does not implement the RFC 012D session observer.');
  }
  return addon.observeSession(request);
}

/**
 * The decode boundary: one wrapper, two transport details.
 *
 * 1. Engine results arrive as JSON encoded on the Rust worker thread. They are
 *    parsed here so the rest of the SDK — and every consumer of it — sees the
 *    generated result contracts rather than strings. A method that returns a
 *    number (`cancelPendingQueries`) or nothing passes through untouched.
 * 2. NAPI-RS observes abort events after a task is created, but an already
 *    aborted signal has no future event to deliver, so an aborted request is
 *    rejected before it reaches Rust.
 *
 * Both belong to the transport, not to the query surface, which is why they
 * live in one place instead of in every method.
 */
function decodeEngineResults(engine: NativeSpaghettiEngine): SpaghettiEngine {
  const decoded = new Proxy(engine, {
    get(target, property) {
      const value: unknown = Reflect.get(target, property, target);
      if (property === 'status') return decodeNativeResult(value);
      if (typeof value !== 'function') return value;
      return (...args: unknown[]) => {
        const aborted = args.find(isAbortedSignal);
        if (aborted) return Promise.reject(aborted.reason ?? abortError());
        const result: unknown = Reflect.apply(value, target, args);
        return isThenable(result) ? result.then(decodeNativeResult) : decodeNativeResult(result);
      };
    },
  });
  return decoded as unknown as SpaghettiEngine;
}

/** JSON in, object out; anything the engine did not encode passes through. */
function decodeNativeResult(value: unknown): unknown {
  return typeof value === 'string' ? JSON.parse(value) : value;
}

function isThenable(value: unknown): value is PromiseLike<unknown> {
  return typeof (value as PromiseLike<unknown> | null)?.then === 'function';
}

function isAbortedSignal(value: unknown): value is AbortSignal {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Partial<AbortSignal>;
  return candidate.aborted === true && typeof candidate.addEventListener === 'function';
}

function abortError(): Error {
  const error = new Error('The operation was aborted.');
  error.name = 'AbortError';
  return error;
}

/**
 * Version of the addon this SDK expects.
 *
 * The two are released in lockstep, so the SDK's own version is the answer.
 * Read at call time from the package manifest rather than baked in, because a
 * baked constant drifts silently the moment a release bumps one and not the
 * other — and this value exists to help diagnose exactly that kind of skew.
 */
function expectedAddonVersion(): string {
  try {
    const require = createRequire(import.meta.url);
    return (require('../package.json') as { version?: string }).version ?? 'unknown';
  } catch {
    return 'unknown';
  }
}

/**
 * Why the native addon is unavailable, or `null` when it loaded.
 *
 * Call after {@link loadNativeAddon}. Production hosts throw this failure at
 * startup; diagnostics can inspect it without opening an engine.
 */
export function nativeLoadFailure(): EngineUnavailableError | null {
  loadNativeAddon();
  return loadFailure;
}

/**
 * Compatibility diagnostic retained for callers from the pre-RFC 011 SDK.
 * Production ingest is always native; availability is reported separately.
 */
export function isNativeIngestEnabled(): boolean {
  return true;
}

/** Rust-only production engine status. */
export interface ActiveEngineInfo {
  /** The sole production engine. */
  engine: IngestEngine;
  /** Retained for response compatibility; always `rs`. */
  preference: IngestEngine;
  /** Whether the native addon (`@vibecook/spaghetti-sdk-native`) loaded. */
  nativeAvailable: boolean;
  /** Loaded native addon semver, or `null` when unavailable. */
  nativeVersion: string | null;
}

/**
 * Resolve production engine availability without inventing a fallback.
 */
export function resolveActiveEngine(): ActiveEngineInfo {
  const native = loadNativeAddon();
  const nativeAvailable = native !== null;
  return {
    engine: 'rs',
    preference: 'rs',
    nativeAvailable,
    nativeVersion: native?.nativeVersion() ?? null,
  };
}
