#!/usr/bin/env node
/**
 * Rust -> TypeScript binding generation (RFC 012 landing plan §5.4).
 *
 * Serde types that cross the native boundary as JSON are declared once, in
 * Rust, with `#[derive(ts_rs::TS)] #[ts(export)]`. ts-rs emits one `#[test]`
 * per exported type (`export_bindings_<lowercased name>`); running those tests
 * writes the bindings. This script runs them with the environment ts-rs reads,
 * then rewrites the directory's barrel so the SDK has one import site.
 *
 * Output lands in `packages/sdk/src/generated/` and is committed. CI's
 * "Generated files are current" step diffs it, so a Rust shape change that is
 * not regenerated fails the build instead of silently drifting from TypeScript.
 *
 * Environment passed to ts-rs:
 * - `TS_RS_EXPORT_DIR`       — absolute output directory.
 * - `TS_RS_IMPORT_EXTENSION` — `js`, matching the SDK's ESM import style.
 * - `TS_RS_LARGE_INT`        — `number`, not the ts-rs default `bigint`. Every
 *   64-bit integer on these contracts is validated in Rust against the
 *   portable safe-integer bound (`validate_portable_u64` / `_i64` in
 *   `adapter/semantic.rs`), so `number` is the honest binding and `bigint`
 *   would be a lie that breaks JSON round-trips.
 *
 * Usage: `pnpm generate:types` (add `--check` to fail instead of writing).
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'packages', 'sdk', 'src', 'generated');
const BARREL = join(OUT_DIR, 'index.ts');

const BARREL_HEADER = `/**
 * Generated by \`pnpm generate:types\` (scripts/generate-types.mjs). DO NOT EDIT.
 *
 * Every type here is declared in Rust and exported by \`ts-rs\`. Hand-writing a
 * TypeScript mirror of native output is forbidden by the RFC 012 landing plan
 * §5.4 — change the Rust definition and regenerate instead.
 */
`;

/** Remove stale bindings so a deleted Rust type cannot linger in the tree. */
function clean() {
  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
    return;
  }
  for (const entry of readdirSync(OUT_DIR)) {
    if (entry.endsWith('.ts')) rmSync(join(OUT_DIR, entry));
  }
}

function exportBindings() {
  execFileSync(
    'cargo',
    ['test', '-p', 'spaghetti-napi', '--lib', 'export_bindings', '--', '--include-ignored'],
    {
      cwd: ROOT,
      stdio: 'inherit',
      env: {
        ...process.env,
        TS_RS_EXPORT_DIR: OUT_DIR,
        TS_RS_IMPORT_EXTENSION: 'js',
        TS_RS_LARGE_INT: 'number',
      },
    },
  );
}

/**
 * ts-rs leaves a trailing space after a field that carries a doc comment,
 * which `git diff --check` rejects. Strip it here so the committed bindings
 * are clean rather than asking every lane to work around it.
 */
function trimTrailingWhitespace() {
  for (const entry of readdirSync(OUT_DIR)) {
    if (!entry.endsWith('.ts')) continue;
    const file = join(OUT_DIR, entry);
    const text = readFileSync(file, 'utf8');
    const cleaned = text.replace(/[ \t]+$/gm, '');
    if (cleaned !== text) writeFileSync(file, cleaned, 'utf8');
  }
}

/** One import site for the SDK: `./generated/index.js`. */
function writeBarrel() {
  const modules = readdirSync(OUT_DIR)
    .filter((entry) => entry.endsWith('.ts') && entry !== 'index.ts')
    .map((entry) => entry.slice(0, -3))
    .sort();
  if (modules.length === 0) {
    throw new Error('generate-types: ts-rs produced no bindings; is `#[ts(export)]` still present?');
  }
  const body = modules.map((name) => `export type { ${name} } from './${name}.js';`).join('\n');
  writeFileSync(BARREL, `${BARREL_HEADER}\n${body}\n`, 'utf8');
  return modules;
}

const check = process.argv.includes('--check');
const before = existsSync(OUT_DIR) ? readdirSync(OUT_DIR).sort().join(',') : '';

clean();
exportBindings();
trimTrailingWhitespace();
const modules = writeBarrel();

if (check) {
  const after = readdirSync(OUT_DIR).sort().join(',');
  if (before !== after) {
    console.error(`generate-types --check: ${OUT_DIR} is stale (${before} -> ${after})`);
    process.exit(1);
  }
}

console.log(`generate-types: wrote ${modules.length} binding(s) to packages/sdk/src/generated/`);
for (const name of modules) console.log(`  - ${name}`);
