/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Run a full ingest of `agent_dir`, writing into the SQLite file at
 * `db_path`. Returns a Promise that resolves to [`IngestStats`] or
 * rejects with a fatal error.
 *
 * Only `mode: "cold"` is implemented in Phase 1.
 *
 * The optional `on_progress` callback is invoked from the libuv
 * worker thread (threadsafe) with snapshots during ingest — start,
 * per-project-complete, and finalize. Throttled implicitly by the
 * coarse "per project" granularity.
 */
export declare function ingest(opts: IngestOptions, onProgress?: (progress: IngestProgress) => void): Promise<IngestStats>

export interface IngestError {
  slug: string
  message: string
}

/**
 * Options for [`ingest`].
 *
 * Mirrors the RFC 003 `IngestOptions` TypeScript shape. Fields that RFC
 * marks optional are `Option<T>` here and get defaulted in
 * [`IngestOptions::resolved`].
 */
export interface IngestOptions {
  /**
   * Agent data root on disk (e.g. `~/.claude` or `~/.codex`).
   * Paired with [`source_id`] to select the reader and stamp rows.
   */
  agentDir: string
  dbPath: string
  /** `"cold"` | `"warm"`. Warm no-ops when fingerprints are unchanged. */
  mode: string
  progressIntervalMs?: number
  parallelism?: number
  /**
   * Agent product id stamped on every core row (default `claude-code`).
   * Optional so existing TS callers that omit it keep working.
   */
  sourceId?: string
  /**
   * When true, bulk ingest stays on WAL + synchronous=NORMAL (desktop-safe).
   * Default / omitted = fast MEMORY + OFF path.
   */
  safeBulk?: boolean
}

/**
 * Progress snapshot for the optional on-progress callback. Fires once
 * on start (`phase = "scanning"`, projects_total set), once per project
 * completion (`phase = "parsing"`), and once at finalization
 * (`phase = "finalizing"`). The JS side can subscribe to drive a
 * progress bar / TUI status line without having to poll.
 */
export interface IngestProgress {
  phase: string
  projectsDone: number
  projectsTotal: number
  elapsedMs: number
}

/**
 * Stats returned on successful ingest.
 *
 * Mirrors the RFC 003 `IngestStats` shape. Errors accumulated during
 * ingest (e.g. bad JSONL lines) are returned in `errors`; fatal errors
 * reject the promise instead.
 */
export interface IngestStats {
  durationMs: number
  projectsProcessed: number
  sessionsProcessed: number
  messagesWritten: number
  subagentsWritten: number
  /**
   * Non-fatal errors collected during ingest — parse failures, missing
   * session files, etc.
   */
  errors: Array<IngestError>
}

/** Result of one `live_ingest_batch` call. */
export interface LiveBatchResult {
  /** One `LiveRowId` per input row, in input order. Empty on empty input. */
  writtenRows: Array<LiveRowId>
  /** Wall-clock duration of the whole call (ms). */
  durationMs: number
}

/**
 * Write a batch of live-update rows to the SQLite DB at `db_path`.
 *
 * Thin NAPI wrapper that delegates to [`live_ingest_batch_inner`] and
 * marshals the error back across the boundary. Keeping the logic in
 * an internal function means `cargo test` can exercise it without
 * linking against Node runtime symbols (`napi_delete_reference` et al.).
 *
 * `source_id` defaults to `claude-code` when omitted so existing TS
 * callers keep working. Multi-source live writers should pass the
 * agent id explicitly (Phase B).
 */
export declare function liveIngestBatch(dbPath: string, rows: Array<LiveRow>, sourceId?: string | undefined | null): LiveBatchResult

/**
 * One row the TS live-update writer wants persisted.
 *
 * `payload_json` is a JSON-encoded payload whose shape depends on
 * `category`; see the module-level table for the mapping.
 */
export interface LiveRow {
  /**
   * One of: `message` | `subagent` | `tool_result` | `file_history` |
   * `todo` | `task` | `plan` | `project_memory` | `session_index`.
   */
  category: string
  /**
   * Project slug, when the row is project-scoped. Absent for
   * session-only rows (file_history / todo / task).
   */
  slug?: string
  /**
   * Session UUID, when the row is session-scoped. Absent for
   * project-only rows (plan / project_memory / session_index).
   */
  sessionId?: string
  /** JSON-encoded payload. The Rust side deserialises per `category`. */
  payloadJson: string
}

/**
 * Identifier of a row the batch successfully wrote. The TS side
 * uses this to reconstruct the matching `Change` event on the
 * live-updates subscriber path.
 */
export interface LiveRowId {
  category: string
  slug?: string
  sessionId?: string
  /**
   * Unique key for the row within its category. For `message` this
   * is the message uuid; for `tool_result` the tool_use_id; for
   * `subagent` the agent_id; for `file_history` the session id;
   * for `todo` the agent_id; for `task` the session id; for `plan`
   * the plan slug; for `project_memory` / `session_index` the
   * project slug.
   */
  rowKey: string
}

/** Returns the semver of the native addon. */
export declare function nativeVersion(): string
